
	<div>
		<table width="100%" border="1" height="80" cellpadding="20">
			<tr>
				<th><a href="http://localhost/project/index.php?c=Product&a=grid">Product</a></th>
				<th><a href="http://localhost/project/Category.php?a=grid">Category</a></th>
				<th><a href="http://localhost/project/Customer.php?a=grid">Customer</a></th>
				<th><a href="http://localhost/project/Vendor.php?a=grid">Vendor</a></th>
				<th><a href="http://localhost/project/Salesman.php?a=grid">Salesman</a></th>
				<th><a href="http://localhost/project/ShippingMethod.php?a=grid">Shiping Method</a></th>
				<th><a href="http://localhost/project/PaymentMethod.php?a=grid">Payment Method</a></th>
			</tr>
		</table>
	</div><br><br>

