<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="Skin/css/add.css?<?php echo time(); ?>">
	<title>Add Product</title>
</head>
<body>

 	<div class="mainContainer">
 		<h3 class="add">Add Product</h3>
 		<form action="Product.php?a=insert" method="post">
 			<table >
 				<tr>
 					<td>Name:</td>
 					<td><input type="text" name="name"></td>
 				</tr>
 				<tr>
 					<td>sku:</td>
 					<td><input type="text" name="sku"></td>
 				</tr>
 				<tr>
 					<td>Cost:</td>
 					<td><input type="text" name="cost"></td>
 				</tr>
 				<tr>
 					<td>Price:</td>
 					<td><input type="text" name="price"></td>
 				</tr>
 				<tr>
 					<td>Quantity:</td>
 					<td><input type="text" name="quantity"></td>
 				</tr>
 				<tr>
 					<td>Description:</td>
 					<td><textarea name="description"></textarea></td>
 				</tr>
 				<tr>
 					<td>Status:</td>
 					<td>
 						<select name="status">
 							<option value="0">Select Status</option>
 							<option value="1">Active</option>
 							<option value="2">Inactive</option>
 						</select>
 					</td>
 				</tr>
 				<tr>
 					<td>Color:</td>
 					<td>
 						<select name="color">
 							<option value="0">Select Color</option>
 							<option value="1">Color 1</option>
 							<option value="2">Color 2</option>
 						</select>
 					</td>
 				</tr>
 				<tr>
 					<td><label>Material:</label></td>
 					<td>
 						<select name="material">
 							<option value="0">Select Material</option>
 							<option value="1">Material 1</option>
 							<option value="2">Material 2</option>
 						</select>
 					</td>
 				</tr>
 			</table>
 			<td><button>submit</button></td>
 		</form>
 	</div>
</body>
</html> 