<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Edit Product</title>
</head>
<body>
	<form action="Product.php?a=update&id=<?php echo($productId) ?>" method="post">
		<table>
			<tr>
				<td>Name:</td>
				<td><input type="text" name="name" value="<?php echo $product['name'] ?>"></td>
			</tr>
			<tr>
				<td>sku:</td>
				<td><input type="text" name="sku" value="<?php echo $product['sku'] ?>"></td>
			</tr>
			<tr>
				<td>Cost:</td>
				<td><input type="text" name="cost" value="<?php echo $product['cost']?>"></td>
			</tr>
			<tr>
				<td>Price:</td>
				<td><input type="text" name="price" value="<?php echo $product['price'] ?>"></td>
			</tr>
			<tr>
				<td>Quantity:</td>
				<td><input type="text" name="quantity" value="<?php echo $product['quantity'] ?>"></td>
			</tr>
			<tr>
				<td>Description:</td>
				<td><input type="text" name="description" value="<?php echo $product['description'] ?>"></td>
			</tr>	
			<tr>
				<td>Status:</td>
				<td>
					<select name="status" value="<?php echo $product['status']?>">
						<option value="0">select status</option>
						<option value="1">active</option>
						<option value="2">inactive</option>
 						</select>
				</td>
			</tr>
			<tr>
				<td>Color:</td>
				<td>
					<select name="color">
						<option value="0"> select Color</option>
						<option value="1"> Color1</option>
						<option value="2"> Color2</option>
					</select>
				</td>
			</tr>
			<tr>
				<td>Material:</td>
				<td>
					<select name="material">
						<option value="0"> select Material </option>
						<option value="1"> Material1 </option>
						<option value="2"> Material2 </option>
					</select>
				</td>
			</tr>
			<tr>
				<button>submit</button>
			</tr>


		</table>
	</form>
</body>
</html>
