<?php
$admins = $this->admins;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Admin</title>
	<link rel="stylesheet" type="text/css" href="Skin/css/style.css">
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>
	<div class="body">
		<div class="box">Manage Admins</div>
		<div class="link"><a href="<?php echo $this->getUrl('add') ?>">Add Admin</a></div>
	</div>
	<table width="100%" cellpadding="30%" border="20px">
		<?php if (!$admins): ?>
		<tr>
			<td colspan="8" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr bgcolor="brown">
			<th>Admin Id</th>
			<th>Name</th>
			<th>email</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($admins as $admin) : ?>
		<tr bgcolor="skyblue">
			<td><?php echo $admin->admin_id; ?></td>
			<td><?php echo $admin->name; ?></td>
			<td><?php echo $admin->email; ?></td>
			<td><?php echo $admin->getStatusText(); ?></td>
			<td><?php echo $admin->created_at; ?></td>
			<td><?php echo $admin->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id' => $admin->admin_id], true) ?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null, ['id' => $admin->admin_id], true) ?>">DELETE</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>