<!DOCTYPE html>
<html>
<?php $this->createBlock('Html_Head')->render(); ?>
<body>
	<table class="w-100" cellpadding="4">
		<tr height="100">
			<td class="bg-primary" colspan=3><?php $this->getChild('header')->render(); ?></td>
		</tr>
		<tr height="40">
			<td  colspan=3><?php $this->getChild('message')->render(); ?></td>
		</tr>
		<tr height="250">
			<td><?php $this->getChild('left')->render(); ?></td>
			<td><?php $this->getChild('content')->render(); ?></td>
			<td><?php $this->getChild('right')->render(); ?></td>
		</tr>
		<tr height="50">
			<td colspan=3><?php $this->getChild('footer')->render(); ?></td>
		</tr>
	</table>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>