<?php
$categories = $this->categories;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Category</title>
	<link rel="stylesheet" type="text/css" href="Skin/css/style.css">
</head>
<body>
	<?php $this->setTemplate('html/header.phtml')->render();?>
	<?php $this->setTemplate('html/message.phtml')->render();?>
	<div class="body">
		<div class="box">Manage Category</div>
		<div class="link">
			<a href="<?php echo $this->getUrl('add', null , [], true);?>">Add Category</a>
		</div>
	</div>
	<table width="100%" cellpadding="30%" border="20px">
		<?php if (!$categories): ?>
		<tr>
			<td colspan="8" align="center"><b>No data found.</b></td>
		</tr>
		<?php else: ?>
		<tr bgcolor="brown">
			<th>Category_id</th>
			<th>Name</th>
			<th>Status</th>
			<th>Description</th>
			<th>Created At</th>
			<th>Updated At</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
		<?php foreach ($categories as $category) : ?>
		<tr bgcolor="skyblue">
			<td><?php echo $category->category_id; ?></td>
			<td><?php echo $category->path; ?></td>
			<td><?php echo $category->getStatusText(); ?></td>
			<td><?php echo $category->description; ?></td>
			<td><?php echo $category->created_at; ?></td>
			<td><?php echo $category->updated_at; ?></td>
			<td><a href="<?php echo $this->getUrl('edit', null, ['id'=> $category->category_id], true);?>">EDIT</a></td>
			<td><a href="<?php echo $this->getUrl('delete', null , ['id'=> $category->category_id], true);?>">DELETE</a></td>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
</body>
</html>